Document: tugas4oss
Title: Debian tugas4oss Manual
Author: <insert document author here>
Abstract: This manual describes what tugas4oss is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tugas4oss/tugas4oss.sgml.gz

Format: postscript
Files: /usr/share/doc/tugas4oss/tugas4oss.ps.gz

Format: text
Files: /usr/share/doc/tugas4oss/tugas4oss.text.gz

Format: HTML
Index: /usr/share/doc/tugas4oss/html/index.html
Files: /usr/share/doc/tugas4oss/html/*.html
